### ISSUE TITLE
NPM lock file

### ISSUE THREAD

**Issue by castastrophe** [RHElements/rhelements#27]
Would recommend committing the package-lock.json file to keep everyone at the same versions.

**Comment by mwcz** [comment]
It is committed: https://github.com/RHElements/rhelements/blob/master/package-lock.json

It's of limited usefulness though since `npm ci` is only available in npm 6 (node 10), but Storybook is incompatible with node 10.  So rhelements is stuck with npm 5 (node 9) until Storybook is fixed.  I'm not sure how to leverage package-lock.json on npm 5.
